name: Terraform Azure Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'  

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Module1
    env:
      ARM_CLIENT_ID: ${{ secrets.ClientID }}
      ARM_CLIENT_SECRET: ${{ secrets.ClientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SubscriptionId }}
      ARM_TENANT_ID: ${{ secrets.TenantId }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4 

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init 

      # Validate Terraform code
      - name: Terraform Validate
        run: terraform validate
        env:
          ARM_CLIENT_ID: ${{ secrets.ClientID }}
          ARM_CLIENT_SECRET: ${{ secrets.ClientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SubscriptionId }}
          ARM_TENANT_ID: ${{ secrets.TenantId }}

      # Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform changes (only on push to main)
      - name: Terraform Apply
        run: terraform apply -auto-approve